import 'package:get/get.dart';

class TransLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'selectTime': 'Select Time',
      'PleaseSelectTimeSlot': 'Please Select Time Slot',
      'noTimeSlotAvailable': 'No Time Slot Available',
      'english': 'English',
      'landscapingConsultation': 'Landscaping Consultation',
      'architectureConsultation': 'Architecture Consultation',
      'interiorConsultation': 'Interior Consultation',
      'office': "Office",
      'site': 'Site',
      'online': 'Online',
      'bookAnAppointment': 'Book an appointment',
      'noCategoryFound': "No Category is Found",
      'bookConsultation': 'Book your consultation now!',
      'selectPreferredTitle': "Select your preferred day and time",
      'pay': 'Pay',
      'WeContactTitle': 'We will contact you!',
      'noServicesFound': "No Services is Found",
      'selectLocation': "Select Location",
      'selectLocationDes':
          "Please select a location where you would like to meet our consultant.",
      'NoConsultationFound': "No consultation is Found",
      'consultant': 'Consultant',
      'PleaseConsultantTitle': 'Please select a consultant',
      'date&Time': 'Date & Time',
      'selectDate': 'Select Date',
      'selectTimeDes': 'No Time Slot Available',
      'slotTimeAlreadyBooked': 'Slot Time Already Booked',
      'warning': 'Warning',
      "continue": 'Continue',
      "summary": 'Summary',
      "personalDetails": 'Personal Details',
      "bookingDetails": 'Booking Details',
      "yourName": 'Your Name',
      "nameValidation": 'name field must not be empty',

      "yourEmail": 'Your email here',
      "emailValidation": 'name field must not be empty',
      "yourPhone": '',
      "phoneValidation": 'phone field must not be empty',
      "yourBooking": 'Your Booking',
      "type": 'Type',
      "date": 'Date',
      "time": 'Time',
      "duration": 'Duration',
      "payment": 'Payment',
      "totalTitle": 'Total',
      "payNow": 'Pay Now',
      'thankYou': 'Thank You',
      'YourAppointmentBeenBook': 'Your Appointment has been booked',
      'AppointmentDetails': 'Appointment Details',
      'Appointment':"Appointment",
      'Service':'Service', 
      'Paid Amount':'Paid Amount',
      'TransactionsId':'Transactions Id',
      'Home':'Home',
      'Something went wrong':'Something went wrong',
      'Oops':'Oops',
      'Payment Failed, please try again':'Payment Failed, please try again',
      'Back':'Back',
      'Hours':'Hours',
    },
    'ar_AR': {
      'selectTime': 'استشارة تصميم مساحات خارجية',

      'noTimeSlotAvailable': 'الموعد غير متوفر',
      'english': 'English',
      'landscapingConsultation': 'استشارة تصميم مساحات خارجية',
      'architectureConsultation': 'استشارة معمارية',
      'interiorConsultation': 'استشارة تصميم داخلي',
      'office': "مكتب",
      'site': 'استشارة موقعية',
      'online': 'اون لاين',
      'bookAnAppointment': 'احجز استشارتك',
      'noCategoryFound': "غير متوفر",
      'bookConsultation': 'احجر استشارتك الآن!',
      'selectPreferredTitle': "اخير اليوم و الوقت الناسب",
      'pay': 'ادفع',
      'WeContactTitle': 'سنتواصل معكم',
      'noServicesFound': "الخدمة غير متوفرة",
      'selectLocation': "حدد الموقع",
      'selectLocationDes': "حدد موقع و عنوان الاستشارة",
      'NoConsultationFound': "الاستشارة غير متوفرة",
      'consultant': 'الاستشاري',
      'PleaseConsultantTitle': 'اختر الاستشاري',
      'date&Time': 'التاريخ و الموعد',
      'selectDate': 'اختر التاريخ',
      'selectTimeDes': 'اختر الوقت',
      'slotTimeAlreadyBooked': 'الموعد محجوز',
      'warning': 'تحذير',
      "continue": 'الاستمرار',
      "summary": 'ملخص',
      "personalDetails": 'البيانات الشخصية',
      "bookingDetails": 'تفاصيل الحجز',
      "yourName": 'الاسم',
      "nameValidation": 'حقل الاسم لا يجب أن يكون فارغًا',

      "yourEmail": 'البريد الاكتروني',
      "emailValidation": 'يجب ألا يكون حقل البريد الإلكتروني فارغًا',
      "yourPhone": '',
      "phoneValidation": 'حقل رقم الهاتف لا يجب أن يكون فارغًا',
      "yourBooking": 'أضف وصفًا (اختياري)',
      "type": 'نوع',
      "date": 'التاريخ',
      "time": 'الوقت',
      "duration": 'المدة',
      "payment": 'الدفع',
      "totalTitle": 'المجموع',
      "payNow": 'ادفع الآن',
      'thankYou': 'شكرًا لك',
      'PleaseSelectTimeSlot': 'يرجى اختيار وقت الموعد',
      'YourAppointmentBeenBook': 'تم حجز موعدك',
      'AppointmentDetails':'تفاصيل الموعد',
      'Appointment':"الموعد",
      'Service':'الخدمة',
      'Paid Amount':'المبلغ المدفوع',
      'TransactionsId':'معرف المعاملة',   
      'Home':'الرئيسية',
      'Something went wrong':'حدث خطأ ما',
      'Oops':'عذرًا',
      'Payment Failed, please try again':'فشل الدفع، يرجى المحاولة مرة أخرى',
      'Back':'العودة',
      'Hours':'ساعات',
    },
  };
}
