// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgCnnBr9VxR8yzeXN3LwkjZqSQ_DJ-iPs',
    appId: '1:654910300478:web:d5fdce2e7000a807e44c6f',
    messagingSenderId: '654910300478',
    projectId: 'propellwebapp',
    authDomain: 'propellwebapp.firebaseapp.com',
    storageBucket: 'propellwebapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgmsQYmxc5Z3ocq2OpMxUROtZ8VwaLURM',
    appId: '1:654910300478:android:b44dc68ac9723936e44c6f',
    messagingSenderId: '654910300478',
    projectId: 'propellwebapp',
    storageBucket: 'propellwebapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Ll_hyO5OfIl2JH_c57FpyLgv2EGz1tg',
    appId: '1:654910300478:ios:809c3ebf0618ec25e44c6f',
    messagingSenderId: '654910300478',
    projectId: 'propellwebapp',
    storageBucket: 'propellwebapp.firebasestorage.app',
    iosBundleId: 'com.propell',
  );

}