// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXsUbrZGqyAHeJMIUOowoDIOra-6bEIdU',
    appId: '1:254485088339:web:551671e5c4b6c24ef71ea6',
    messagingSenderId: '254485088339',
    projectId: 'propell-c04bd',
    authDomain: 'propell-c04bd.firebaseapp.com',
    databaseURL: 'https://propell-c04bd-default-rtdb.firebaseio.com',
    storageBucket: 'propell-c04bd.firebasestorage.app',
    measurementId: 'G-VGS8LFNGGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx_iI0vMB7_CCLGRfxk1-cKk48hIPewoc',
    appId: '1:254485088339:android:54dfa1d7ad6ce432f71ea6',
    messagingSenderId: '254485088339',
    projectId: 'propell-c04bd',
    databaseURL: 'https://propell-c04bd-default-rtdb.firebaseio.com',
    storageBucket: 'propell-c04bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1Ed1CkZF9tnyrrJtk9zH2LzMmrt-hWoI',
    appId: '1:254485088339:ios:046e06a0708257ebf71ea6',
    messagingSenderId: '254485088339',
    projectId: 'propell-c04bd',
    databaseURL: 'https://propell-c04bd-default-rtdb.firebaseio.com',
    storageBucket: 'propell-c04bd.firebasestorage.app',
    iosBundleId: 'com.propell',
  );
}
