// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB50WmRmVqOpxzFICXpQ_AQvIWkFZiKbXY',
    appId: '1:311844172470:web:5688cffc83f96938a02c17',
    messagingSenderId: '311844172470',
    projectId: 'mypropellapp',
    authDomain: 'mypropellapp.firebaseapp.com',
    storageBucket: 'mypropellapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpPW5mmqVA2Ah-9oGLPTumq0BC1rho-TQ',
    appId: '1:311844172470:android:ed8d6aadbb53bb86a02c17',
    messagingSenderId: '311844172470',
    projectId: 'mypropellapp',
    storageBucket: 'mypropellapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvPeLEJN89_p6QIBbMqkBwTAMowLQBFW0',
    appId: '1:311844172470:ios:536c6b186eb6fed4a02c17',
    messagingSenderId: '311844172470',
    projectId: 'mypropellapp',
    storageBucket: 'mypropellapp.firebasestorage.app',
    iosBundleId: 'com.propell',
  );
}
